---
- name: zabbix
  hosts: all
  become: yes

  tasks:
  - name: setup pkg
    shell: wget https://repo.zabbix.com/zabbix/5.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.2-1+ubuntu$(lsb_release -rs)_all.deb && sudo dpkg -i zabbix-release_5.2-1+ubuntu$(lsb_release -rs)_all.deb && sudo apt update -y

  - name: install Packages
    apt:
      state: present
      name:
        - zabbix-server-mysql
        - zabbix-frontend-php
        - zabbix-apache-conf
        - zabbix-agent
        - python3-pip
        - mysql-server
        - php
  - name: Install PyMySQL
    pip:
      name: PyMySQL
  - name: create Database
    shell: sudo mysql -uroot -e "create database zabbix character set utf8 collate utf8_bin;"
    ignore_errors: yes

    #- name: mysql database creation
    #mysql_db:
    #login_unix_socket: /var/run/mysqld/mysqld.sock
    # name: zabbix
    # state: present
    # encoding: utf8

  - name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
    mysql_user:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: zabbix
      password: "zabbix"
      priv: '*.*:ALL,GRANT'
      state: present
  - name: Creating dump.sql
    shell: sudo zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz > /tmp/dump.sql

  - name: Restore database ignoring errors
    mysql_db:
      name: zabbix
      state: import
      target: /tmp/dump.sql
      login_user: zabbix
      login_password: zabbix
    ignore_errors: yes
  - name: Copy zabbix_server.conf
    copy:
      src: zabbix_server.conf
      dest: /etc/zabbix/zabbix_server.conf
  - name: Starting Zabbix Server
    service:
      state: started
      enabled: yes
      name: zabbix-server
  - name: Starting Zabbix Agent
    service:
      state: started
      enabled: yes
      name: zabbix-agent
  - name: COpy apache.conf
    copy:
      src: apache.conf
      dest: /etc/zabbix/apache.conf
  - name: Restarting Apache
    service:
      state: restarted
      name: apache2
      enabled: yes